// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc_order

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        int64
	UserID    int64
	Status    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type OrderItem struct {
	OrderID   int64
	Sku       int64
	Count     int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Outbox struct {
	ID          int64
	Topic       string
	Event       []byte
	Headers     []byte
	CreatedAt   pgtype.Timestamp
	CompletedAt pgtype.Timestamp
}

type Stock struct {
	Sku        int64
	TotalCount int32
	Reserved   int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
